export enum LogEventTypes {
  // Worker Events
  RECEIVED_WORKER_PROCESSING_REQUEST = 'RECEIVED_WORKER_PROCESSING_REQUEST',
  WORKER_PROCESSING_STARTED = 'WORKER_PROCESSING_STARTED',
  WORKER_PROCESSING_COMPLETED = 'WORKER_PROCESSING_COMPLETED',
  ERROR_WORKER_PROCESSING = 'ERROR_WORKER_PROCESSING',
  ERROR_WORKER_TRANSACTION_NOT_FOUND = 'ERROR_WORKER_TRANSACTION_NOT_FOUND',
}

