export enum HttpErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  NO_METHOD_FOUND = 'NO_METHOD_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum HttpResponseCode {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,

  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  SERVICE_UNAVAILABLE = 503,
}

export enum LogEventTypes {
  // API Request Events
  RECEIVED_WEBHOOK_REQUEST = 'RECEIVED_WEBHOOK_REQUEST',
  RECEIVED_HEALTH_CHECK_REQUEST = 'RECEIVED_HEALTH_CHECK_REQUEST',
  RECEIVED_TRANSACTION_STATUS_REQUEST = 'RECEIVED_TRANSACTION_STATUS_REQUEST',
  
  // Success Events
  WEBHOOK_PROCESSED_SUCCESS = 'WEBHOOK_PROCESSED_SUCCESS',
  TRANSACTION_STATUS_RETRIEVED = 'TRANSACTION_STATUS_RETRIEVED',
  HEALTH_CHECK_SUCCESS = 'HEALTH_CHECK_SUCCESS',
  
  // Error Events
  ERROR_WEBHOOK_REQUEST = 'ERROR_WEBHOOK_REQUEST',
  ERROR_TRANSACTION_STATUS_REQUEST = 'ERROR_TRANSACTION_STATUS_REQUEST',
  ERROR_NO_METHOD_FOUND = 'ERROR_NO_METHOD_FOUND',
  ERROR_INVALID_PAYLOAD = 'ERROR_INVALID_PAYLOAD',
  ERROR_DUPLICATE_TRANSACTION = 'ERROR_DUPLICATE_TRANSACTION',
  
  // Worker Events
  RECEIVED_WORKER_PROCESSING_REQUEST = 'RECEIVED_WORKER_PROCESSING_REQUEST',
  WORKER_PROCESSING_STARTED = 'WORKER_PROCESSING_STARTED',
  WORKER_PROCESSING_COMPLETED = 'WORKER_PROCESSING_COMPLETED',
  ERROR_WORKER_PROCESSING = 'ERROR_WORKER_PROCESSING',
}

